services:
  idp:
    container_name: idp
    image: ghcr.io/identicum/keycloak:26.1
    restart: always
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
    ports:
      - 8080:8080
    command: start

  idp_setup:
      container_name: idp_setup
      image: ghcr.io/identicum/sherpa-deploy:latest
      pull_policy: always
      volumes:
          - ../:/usr/home/
      # command: "./testing/deploy.py"
      depends_on:
          idp:
              condition: service_healthy
